# Generated by Django 5.0.1 on 2024-02-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_admission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Person_name', models.CharField(max_length=25)),
                ('card_number', models.CharField(max_length=15)),
                ('expiry', models.DateField()),
                ('cvv', models.CharField(max_length=3)),
            ],
        ),
    ]
