# Generated by Django 5.0.1 on 2024-02-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='phone',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_number',
            field=models.IntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cvv',
            field=models.IntegerField(max_length=3),
        ),
    ]
