# Generated by Django 5.0.1 on 2024-02-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_admission_phone_alter_payment_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Person_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_number',
            field=models.CharField(max_length=15),
        ),
    ]
