# Generated by Django 5.0.1 on 2024-03-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_delete_confirmationpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Person_name',
            field=models.CharField(max_length=100),
        ),
    ]
