# Generated by Django 5.0.1 on 2024-03-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_payment_person_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Person_name',
            field=models.CharField(max_length=20),
        ),
    ]
